name: Continuous Integration

on:
  pull_request:
    branches: [main]

jobs:
  frontend-test:
    name: Frontend testing
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install pnpm and Node.js
        uses: pnpm/setup@v2
        with:
          runtime: node@24

      - name: Check formatting
        run: pnpm format:check

      - name: Lint files
        run: pnpm lint:check

      - name: Run Vitest unit tests
        run: pnpm test

      - name: Install Chromium
        run: pnpm exec playwright install chromium --only-shell

      - name: Run Playwright component tests
        run: pnpm playwright
