name: Continuous Integration

on:
  pull_request:
    branches: [main]

jobs:
  frontend-test:
    name: Frontend testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup PNPM
        uses: pnpm/action-setup@v6
        with:
          cache: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check formatting
        run: pnpm format:check

      - name: Lint files
        run: pnpm lint:check

      - name: Run Vitest unit tests
        run: pnpm test

      - name: Install Chromium
        run: pnpm exec playwright install chromium --only-shell

      - name: Run Playwright component tests
        run: pnpm playwright
