name: Continuous Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build & Deploy to Firebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Enable pnpm
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Astro build
        run: pnpm build

      - name: Deploy Astro to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Build Storybook
        run: pnpm storybook build

      - name: Upload Storybook Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./storybook-static

  deploy-pages:
    name: Deploy Storybook to GitHub Pages
    needs: build
    runs-on: ubuntu-latest

    # Required permissions for native GitHub Pages deployment
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
