name: Continuous Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Firebase hosting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Enable pnpm
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Astro and Storybook
        run: |
          pnpm build
          pnpm storybook-build

      - name: Deploy Astro to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:main-site
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy Storybook to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:storybook
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
